name: Download Artifact

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read

    steps:
      - name: Download artifact
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run download \
            30427294024 \
            -n PopStudio-armeabi-v7a \
            -D artifact

      - name: List files
        run: |
          find artifact -type f