name: Download Artifact

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read

    steps:
      - name: Download artifact
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run download \
            30427294024 \
            -n PopStudio-armeabi-v7a \
            -D artifact

      - name: List files
        run: |
          find artifact -type f

      - name: Extract APK
        run: |
          APK=$(find artifact -name "*.apk" | head -n 1)
          cp "$APK" app.zip
          mkdir extracted
          unzip -q app.zip -d extracted

      - name: Show largest files
        run: |
          find extracted -type f -printf "%s %p\n" | sort -nr | head -100